version: "3.8"

services:
  itsu-excel:
    image: itsu-excel:latest
    container_name: itsu-excel
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8080/actuator/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s